<?php
namespace Librinfo\EmailBundle\tests\Functional;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-02 at 09:40:35.
 */

use PHPUnit\Framework\TestCase;

class EmailAdmin extends TestCase
{
    /**
     * @var EmailAdmin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EmailAdmin;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailAdmin::postConfigureFormFields
     * @todo   Implement testPostConfigureFormFields().
     */
    public function testPostConfigureFormFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailAdmin::prePersist
     * @todo   Implement testPrePersist().
     */
    public function testPrePersist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailAdmin::preUpdate
     * @todo   Implement testPreUpdate().
     */
    public function testPreUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailAdmin::getNewInstance
     * @todo   Implement testGetNewInstance().
     */
    public function testGetNewInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailAdmin::getPersistentParameters
     * @todo   Implement testGetPersistentParameters().
     */
    public function testGetPersistentParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailAdmin::getExportFormats
     * @todo   Implement testGetExportFormats().
     */
    public function testGetExportFormats()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailAdmin::getExportFields
     * @todo   Implement testGetExportFields().
     */
    public function testGetExportFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailAdmin::getDataSourceIterator
     * @todo   Implement testGetDataSourceIterator().
     */
    public function testGetDataSourceIterator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailAdmin::getBatchActions
     * @todo   Implement testGetBatchActions().
     */
    public function testGetBatchActions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
