<?php
namespace Librinfo\EmailBundle\tests\Functional;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-02 at 09:44:02.
 */

use PHPUnit\Framework\TestCase;

class EmailLinkAdmin extends TestCase
{
    /**
     * @var EmailLinkAdmin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EmailLinkAdmin;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailLinkAdmin::getExportFormats
     * @todo   Implement testGetExportFormats().
     */
    public function testGetExportFormats()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailLinkAdmin::getExportFields
     * @todo   Implement testGetExportFields().
     */
    public function testGetExportFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailLinkAdmin::getDataSourceIterator
     * @todo   Implement testGetDataSourceIterator().
     */
    public function testGetDataSourceIterator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Admin\EmailLinkAdmin::getBatchActions
     * @todo   Implement testGetBatchActions().
     */
    public function testGetBatchActions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
