<?php
namespace Librinfo\EmailBundle\tests\Functional;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-28 at 14:48:08.
 * Modified by Quotidianus
 */

use PHPUnit\Framework\TestCase;
use Librinfo\EmailBundle\Services\Sender;

class SenderTest extends TestCase
{
    /**
     * @var Sender
     */
    protected $object;
    
    private $manager;
    private $tracker;
    private $inlineAttachmentsHandler;
    private $directMailer;
    private $spoolMailer;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    $this->manager = $this->createMock('Doctrine\ORM\EntityManager');
    $this->tracker = $this->createMock('Librinfo\EmailBundle\Services\Tracking');
    $this->inlineAttachmentsHandler = $this->createMock('Librinfo\EmailBundle\Services\InlineAttachments');              
    $this->directMailer = $this->createMock('Swift_Mailer');     
    /*
    * todo : check if we need to mock for this same object
    */         
    $this->spoolMailer = $this->createMock('Swift_Mailer');              
    
    $this->object = new Sender(
        $this->manager,
        $this->tracker,
        $this->inlineAttachmentsHandler,
        $this->directMailer, 
        $this->spoolMailer
    );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Librinfo\EmailBundle\Services\Sender::send
     * @todo   Implement testSend().
     */
    public function testSend()
    {
    /*
    * $this->assertFileExists($this->attachmentsFile)
    */
	
    }
}
