<?php
namespace Librinfo\EmailBundle\tests\Functional;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-04 at 15:18:32.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\EmailBundle\Entity\Email;

class EmailTest extends TestCase
{
    /**
     * @var Email
     */
    protected $emailtest;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->emailtest = new Email;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::initCollections
     * @todo   Implement testInitCollections().
     */
    public function testInitCollections()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::__clone
     * @todo   Implement test__clone().
     */
    public function test__clone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setFieldFrom
     */
    public function testSetFieldFrom()
    {
        $this->emailtest->setFieldFrom('you@me.us');
        $this->assertEquals('you@me.us', $this->emailtest->getFieldFrom());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getFieldFrom
     */
    public function testGetFieldFrom()
    {
        $from = $this->emailtest->getFieldFrom();
        $this->assertEquals($from,'');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setFieldTo
     */
    public function testSetFieldTo()
    {
        $this->emailtest->setFieldTo('me@you.us');
        $this->assertEquals('me@you.us', $this->emailtest->getFieldTo());
     }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getFieldTo
     */
    public function testGetFieldTo()
    {
        $to = $this->emailtest->getFieldTo();
        $this->assertEquals($to,'');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setFieldCc
     */
    public function testSetFieldCc()
    {
        $this->emailtest->setFieldCc('me@he.us');
        $this->assertEquals('me@he.us', $this->emailtest->getFieldCc());
     }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getFieldCc
     */
    public function testGetFieldCc()
    {
        $tocc = $this->emailtest->getFieldCc();
        $this->assertEquals($tocc,'');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setFieldBcc
     */
    public function testSetFieldBcc()
    {
        $this->emailtest->setFieldBcc('me@they.us');
        $this->assertEquals('me@they.us', $this->emailtest->getFieldBcc());
     }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getFieldBcc
     */
    public function testGetFieldBcc()
    {
        $tobcc = $this->emailtest->getFieldBcc();
        $this->assertEquals($tobcc,'');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setFieldSubject
     */
    public function testSetFieldSubject()
    {
        $this->emailtest->setFieldSubject('Email subject');
        $this->assertEquals('Email subject', $this->emailtest->getFieldSubject());
     }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getFieldSubject
     */
    public function testGetFieldSubject()
    {
        $subject = $this->emailtest->getFieldSubject();
        $this->assertEquals($subject,'<no subject>');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setContent
     */
    public function testSetContent()
    {
        $this->emailtest->setContent('Email html content');
        $this->assertEquals('Email html content', $this->emailtest->getContent());
     }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getContent
     */
    public function testGetContent()
    {
        $content = $this->emailtest->getContent();
        $this->assertEquals($content,'');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setTextContent
     */
    public function testSetTextContent()
    {
        $this->emailtest->setTextContent('Email text content');
        $this->assertEquals('Email text content', $this->emailtest->getTextContent());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getTextContent
     */
    public function testGetTextContent()
    {
        $textcontent = $this->emailtest->getTextContent();
        $this->assertEquals($textcontent,'');
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setSent
     */
    public function testSetSent()
    {
        $this->emailtest->setSent(true);
        $this->assertTrue($this->emailtest->getSent());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getSent
     */
    public function testGetSent()
    {
        $sent = $this->emailtest->getSent();
        $this->assertFalse($sent);
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::addAttachment
     * @todo   Implement testAddAttachment().
     */
    public function testAddAttachment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::addLibrinfoFile
     * @todo   Implement testAddLibrinfoFile().
     */
    public function testAddLibrinfoFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::removeAttachment
     * @todo   Implement testRemoveAttachment().
     */
    public function testRemoveAttachment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::removeLibrinfoFile
     * @todo   Implement testRemoveLibrinfoFile().
     */
    public function testRemoveLibrinfoFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getAttachments
     * @todo   Implement testGetAttachments().
     */
    public function testGetAttachments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getLibrinfoFiles
     * @todo   Implement testGetLibrinfoFiles().
     */
    public function testGetLibrinfoFiles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setAttachments
     * @todo   Implement testSetAttachments().
     */
    public function testSetAttachments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setIsTest
     */
    public function testSetIsTest()
    {
        $this->emailtest->setIsTest(true);
        $this->assertTrue($this->emailtest->getIsTest());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getIsTest
     */
    public function testGetIsTest()
    {
        $istest = $this->emailtest->getIsTest();
        $this->assertFalse($istest);
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getTestAddress
     * @todo   Implement testGetTestAddress().
     */
    public function testGetTestAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setTestAddress
     * @todo   Implement testSetTestAddress().
     */
    public function testSetTestAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getTemplate
     * @todo   Implement testGetTemplate().
     */
    public function testGetTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setTemplate
     * @todo   Implement testSetTemplate().
     */
    public function testSetTemplate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setIsTemplate
     */
    public function testSetIsTemplate()
    {
        $this->emailtest->setIsTemplate(true);
        $this->assertTrue($this->emailtest->getIsTemplate());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getIsTemplate
     */
    public function testGetIsTemplate()
    {
        $istemplate = $this->emailtest->getIsTemplate();
        $this->assertFalse($istemplate);
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getNewTemplateName
     * @todo   Implement testGetNewTemplateName().
     */
    public function testGetNewTemplateName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setNewTemplateName
     * @todo   Implement testSetNewTemplateName().
     */
    public function testSetNewTemplateName()
    {
        $this->emailtest->setNewTemplateName('New template name');
        $this->assertEquals('New template name', $this->emailtest->getNewTemplateName());
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setTracking
     * @todo   Implement testSetTracking().
     */
    public function testSetTracking()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getTracking
     * @todo   Implement testGetTracking().
     */
    public function testGetTracking()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::addReceipt
     * @todo   Implement testAddReceipt().
     */
    public function testAddReceipt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::removeReceipt
     * @todo   Implement testRemoveReceipt().
     */
    public function testRemoveReceipt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getReceipts
     * @todo   Implement testGetReceipts().
     */
    public function testGetReceipts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::addLink
     * @todo   Implement testAddLink().
     */
    public function testAddLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::removeLink
     * @todo   Implement testRemoveLink().
     */
    public function testRemoveLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getLinks
     * @todo   Implement testGetLinks().
     */
    public function testGetLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setId
     * @todo   Implement testSetId().
     */
    public function testSetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::isNew
     * @todo   Implement testIsNew().
     */
    public function testIsNew()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::addSearchIndex
     * @todo   Implement testAddSearchIndex().
     */
    public function testAddSearchIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::removeSearchIndex
     * @todo   Implement testRemoveSearchIndex().
     */
    public function testRemoveSearchIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getSearchIndexes
     * @todo   Implement testGetSearchIndexes().
     */
    public function testGetSearchIndexes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setSearchIndexes
     * @todo   Implement testSetSearchIndexes().
     */
    public function testSetSearchIndexes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::analyseField
     * @todo   Implement testAnalyseField().
     */
    public function testAnalyseField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getCreatedAt
     * @todo   Implement testGetCreatedAt().
     */
    public function testGetCreatedAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setCreatedAt
     * @todo   Implement testSetCreatedAt().
     */
    public function testSetCreatedAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::getUpdatedAt
     * @todo   Implement testGetUpdatedAt().
     */
    public function testGetUpdatedAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\EmailBundle\Entity\Email::setUpdatedAt
     * @todo   Implement testSetUpdatedAt().
     */
    public function testSetUpdatedAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
